### ISSUE TITLE
can't upgrade Laravel to version 6.0

### ISSUE THREAD

**Issue by aswierc** [primitivesense/laravel-raw-sqs-connector#2]
Hey guys, I use your library, but now I can't upgrade Laravel to version 6.x because of that you have a hard-dependency with **"illuminate/queue": "^5.8"**

Did you think about changing it to open the upgrade of Laravel?

**Comment by harnasz** [comment]
Hey @aswierc - we sure can. I've seen the MR here - https://github.com/primitivesense/laravel-raw-sqs-connector/pull/3

We will be best bumping the tag on this library to `2.0` for the 6+ Laravel release.   and amending the Travis CI definition to remove the PHP 7.2 step.

**Comment by harnasz** [comment]
Hi @aswierc - I've made a new release which can be found here:

https://github.com/primitivesense/laravel-raw-sqs-connector/releases/tag/v2.0.0

It includes your implements change along with the `6.0` queue library and ensuring PHP 7.3 above.

**Comment by harnasz** [comment]
Sorry just to ask @aswierc  - please let me know if that solves your issues.

**Comment by aswierc** [comment]
@harnasz thank you so much for the fast reaction! I'll check it tomorrow

**Comment by aswierc** [comment]
hey @harnasz it seems to works well, I just did some simple tests, and important for me is I can upgrade Laravel. I'll let you know if something will be wrong with it. Thanks!

**Comment by harnasz** [comment]
No problem at all!
