### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by patryyyck** [primitivesense/laravel-raw-sqs-connector#8]
Hi,

This package sounds great ... but i can't install it :-(

I use php 7.4.15 with "laravel/framework" v8.31.0 and i have the following message:

```
  Problem 1
    - Root composer.json requires primitivesense/laravel-raw-sqs-connector ^2.0 -> satisfiable by primitivesense/laravel-raw-sqs-connector[v2.0].
    - primitivesense/laravel-raw-sqs-connector v2.0 requires illuminate/queue ^6.0 -> found illuminate/queue[v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Thanks for your help.

Regards

**Comment by harnasz** [comment]
Hi @patryyyck!  Hope you're well.  I'll look to to try and get this sorted for you in the next day or so! If I send you a dev tag would you mind testing the changes for me?

**Comment by patryyyck** [comment]
hi @harnasz ,
of course! You're welcome.  ;-)

**Comment by juliomenendez** [comment]
hi @patryyyck! Any update on Laravel 8 support? Thanks in advance!!

**Comment by juliomenendez** [comment]
Just in case, I did the upgrade and seems to be working fine.

**Comment by harnasz** [comment]
Hey @juliomenendez - Thanks for very much for the the PR. I've now tagged this as v3.0.0. @patryyyck very sorry for the slow response on this.
